### ISSUE TITLE
Device on battery

### ISSUE THREAD

**Issue by GregoryChavanel** [roblans/ZWave4Net#5]
Hello,
I try to communicate with my thermostat. which is on battery
[http://www.securemeters.com/europe/products/system-products/thermostats/srt321-thermostat](url)
But i have this error : Transmission failure: CompleteNoAcknowledge.

I would like to know if you implement devices on battery ? if yes, how can i communicate with it ?

Thanks for your help.
Greg

**Comment by roblans** [comment]
Yes, battery devices are fully supported. Note, however, that you can only communicate with a battery powered node when it's Awake. If you send a command to a node that's not awake then you will get a TimeoutException.  The CompleteNoAcknowledge mostly happens if you're sending a unknown or invalid command to a node. Does the problem occurs with all commands?

Rob.

**Comment by GregoryChavanel** [comment]
You're right. my device was not awake.
I found the class WakeUp. And now, when the event arrives, i can send my command.
Thanks for your reply and your work
Greg
